     <thead>
                    <tr>
                        <th>Titel</th>
                        <th>Edit</th>
                        <th>Delete</th>
                        <th>Online/Offline</th>
                        <th>Main</th>
                    </tr>
    </thead>