     <thead>
                    <tr>
                    <th>Naam</th>
                    <th>Email</th>
                    <th>Birthday</th>
                    <th>Section</th>
                    <th>Phonenumber</th>
                    <th>Roles</th>
                    <th>Delete</th>
                    <th>Edit</th>
                    </tr>
    </thead>